create database QUAN_LY_GIAI_BONG_DA
go
use QUAN_LY_GIAI_BONG_DA;

CREATE TABLE CAUTHU (
	MACT NUMERIC IDENTITY(1,1) PRIMARY KEY,
	HOTEN NVARCHAR(100) not null,
	VITRI NVARCHAR(20) not null,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MACLB VARCHAR(5) not null, 
	MAQG VARCHAR(5) NOT NULL,
	SO INT NOT NULL,
);

CREATE TABLE QUOCGIA (
    MAQG VARCHAR(5) PRIMARY KEY,
    TENQG NVARCHAR(100) NOT NULL
);

CREATE TABLE CAULACBO (
	MACLB VARCHAR(5) PRIMARY KEY,
	TENCLB NVARCHAR(100) NOT NULL,
	MASAN VARCHAR(5) NOT NULL,
	MATINH VARCHAR(5) NOT NULL
);

CREATE TABLE TINH (
	MATINH VARCHAR(5) PRIMARY KEY,
	TENTINH NVARCHAR(100) NOT NULL
);

CREATE TABLE SANVD (
	MASAN VARCHAR(5) PRIMARY KEY,
	TENSAN NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(200)
);

CREATE TABLE HUANLUYENVIEN (
	MAHLV VARCHAR(5) PRIMARY KEY,
	TENHLV NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	DIENTHOAI NVARCHAR(20),
	MAQG VARCHAR(5) NOT NULL
);

CREATE TABLE HLV_CLB (
	MAHLV VARCHAR(5),
	MACLB VARCHAR(5),
	VAITRO NVARCHAR(100) NOT NULL,

	CONSTRAINT PK_HLV_CLB PRIMARY KEY (MAHLV, MACLB)
);

CREATE TABLE TRANDAU (
	MATRAN NUMERIC IDENTITY(1,1) PRIMARY KEY,
	NAM INT NOT NULL,
	VONG INT NOT NULL,
	NGAYTD DATETIME NOT NULL,
	MACLB1 VARCHAR(5) NOT NULL,
	MACLB2 VARCHAR(5) NOT NULL,
	MASAN VARCHAR(5) NOT NULL,
	KETQUA VARCHAR(5) NOT NULL
);

CREATE TABLE BANGXH (
	MACLB VARCHAR(5),
	NAM INT,
	VONG INT,
	SOTRAN INT NOT NULL,
	THANG INT NOT NULL,
	HOA INT NOT NULL,
	THUA INT NOT NULL,
	HIEUSO VARCHAR(5) NOT NULL,
	DIEM INT NOT NULL,
	HANG INT NOT NULL,

	CONSTRAINT PK_BXH PRIMARY KEY (MACLB, NAM, VONG)
);

ALTER TABLE TRANDAU
ADD CONSTRAINT FK_TRANDAU_SANVD
FOREIGN KEY (MASAN) REFERENCES SANVD(MASAN);

ALTER TABLE TRANDAU
ADD CONSTRAINT FK_TRANDAU_CAULACBO1
FOREIGN KEY (MACLB1) REFERENCES CAULACBO(MACLB);

ALTER TABLE TRANDAU
ADD CONSTRAINT FK_TRANDAU_CAULACBO2
FOREIGN KEY (MACLB2) REFERENCES CAULACBO(MACLB);

ALTER TABLE CAULACBO
ADD CONSTRAINT FK_CAULACBO_SANVD
FOREIGN KEY (MASAN) REFERENCES SANVD(MASAN);

ALTER TABLE CAULACBO
ADD CONSTRAINT FK_CAULACBO_TINH
FOREIGN KEY (MATINH) REFERENCES TINH(MATINH);

ALTER TABLE HUANLUYENVIEN
ADD CONSTRAINT FK_HUANLUYENVIEN_QUOCGIA
FOREIGN KEY (MAQG) REFERENCES QUOCGIA(MAQG);

ALTER TABLE CAUTHU
ADD CONSTRAINT FK_CAUTHU_QUOCGIA
FOREIGN KEY (MAQG) REFERENCES QUOCGIA(MAQG);

ALTER TABLE CAUTHU
ADD CONSTRAINT FK_CAUTHU_CAULACBO
FOREIGN KEY (MACLB) REFERENCES CAULACBO(MACLB);

ALTER TABLE HLV_CLB
ADD CONSTRAINT FK_HLV_CLB_CAULACBO
FOREIGN KEY (MACLB) REFERENCES CAULACBO(MACLB);

ALTER TABLE HLV_CLB
ADD CONSTRAINT FK_HLV_CLB_HUANLUYENVIEN
FOREIGN KEY (MAHLV) REFERENCES HUANLUYENVIEN(MAHLV);

ALTER TABLE BANGXH
ADD CONSTRAINT FK_BANGXH_CAULACBO
FOREIGN KEY (MACLB) REFERENCES CAULACBO(MACLB);

SET DATEFORMAT MDY;

INSERT INTO QUOCGIA (MAQG, TENQG) VALUES
('VN', N'Việt Nam'),
('ANH', N'Anh Quốc'),
('TBN', N'Tây Ban Nha'),
('BDN', N'Bồ Đào Nha'),
('BRA', N'Brazil'),
('ITA', N'Ý'),
('THA', N'Thái Lan');

INSERT INTO SANVD (MASAN, TENSAN, DIACHI) VALUES
('GD', N'Gò Đậu', N'123 QL1, TX Thủ Dầu Một, Bình Dương'),
('PL', N'Pleiku', N'22 Hồ Tùng Mậu, Thống Nhất, Thị xã Pleiku, Gia Lai'),
('CL', N'Chi Lăng', N'127 Võ Văn Tần, Đà Nẵng'),
('NT', N'Nha Trang', N'128 Phan Chu Trinh, Nha Trang, Khánh Hoà'),
('TH', N'Tuy Hoà', N'57 Trường Chinh, Tuy Hoà, Phú Yên'),
('LA', N'Long An', N'102 Hùng Vương, Tp Tân An, Long An');

INSERT INTO TINH (MATINH, TENTINH) VALUES
('BD', N'Bình Dương'),
('GL', N'Gia Lai'),
('DN', N'Đà Nẵng'),
('KH', N'Khánh Hoà'),
('PY', N'Phú Yên'),
('LA', N'Long An');

INSERT INTO CAULACBO (MACLB, TENCLB, MASAN, MATINH) VALUES
('BBD', N'BECAMEX BÌNH DƯƠNG', 'GD', 'BD'),
('HAGL', N'HOÀNG ANH GIA LAI', 'PL', 'GL'),
('SDN', N'SHB ĐÀ NẴNG', 'CL', 'DN'),
('KKH', N'KHATOCO KHÁNH HOÀ', 'NT', 'KH'),
('TPY', N'THÉP PHÚ YÊN', 'TH', 'PY'),
('GDT', N'GẠCH ĐỒNG TÂM LONG AN', 'LA', 'LA');

INSERT INTO CAUTHU (HOTEN, VITRI, NGAYSINH, DIACHI, MACLB, MAQG, SO) VALUES
(N'Nguyễn Vũ Phong', N'Tiền vệ', '02-20-1990', NULL, 'BBD', 'VN', 17),
(N'Nguyễn Công Vinh', N'Tiền đạo', '03-10-1992', NULL, 'HAGL', 'VN', 9),
(N'Trần Tấn Tài', N'Tiền vệ', '11-12-1989', NULL, 'BBD', 'VN', 8),
(N'Phan Hồng Sơn', N'Thủ môn', '06-10-1991', NULL, 'HAGL', 'VN', 1),
(N'Ronaldo', N'Tiền vệ', '12-12-1989', NULL, 'SDN', 'BRA', 7),
(N'Robinho', N'Tiền vệ', '10-12-1989', NULL, 'SDN', 'BRA', 8),
(N'Vidic', N'Hậu vệ', '10-15-1987', NULL, 'HAGL', 'ANH', 3),
(N'Trần Văn Santos', N'Thủ môn', '10-21-1990', NULL, 'BBD', 'BRA', 1),
(N'Nguyễn Trường Sơn', N'Hậu vệ', '08-26-1993', NULL, 'BBD', 'VN', 4);

INSERT INTO HUANLUYENVIEN (MAHLV, TENHLV, NGAYSINH, DIACHI, DIENTHOAI, MAQG) VALUES
('HLV01', N'Vital', '10-15-1955', NULL, '0918011075', 'BDN'),
('HLV02', N'Lê Huỳnh Đức', '05-20-1972', NULL, '01223456789', 'VN'),
('HLV03', N'Kiatisuk', '12-11-1970', NULL, '01990123456', 'THA'),
('HLV04', N'Hoàng Anh Tuấn', '06-10-1970', NULL, '0989112233', 'VN'),
('HLV05', N'Trần Công Minh', '07-07-1973', NULL, '0909099990', 'VN'),
('HLV06', N'Trần Văn Phúc', '03-02-1965', NULL, '01650101234', 'VN');

INSERT INTO HLV_CLB (MAHLV, MACLB, VAITRO) VALUES
('HLV01','BBD', N'HLV Chính'),
('HLV02','SDN', N'HLV Chính'),
('HLV03','HAGL', N'HLV Chính'),
('HLV04','KKH', N'HLV Chính'),
('HLV05','GDT', N'HLV Chính'),
('HLV06','BBD', N'HLV thủ môn');

INSERT INTO TRANDAU (NAM, VONG, NGAYTD, MACLB1, MACLB2, MASAN, KETQUA) VALUES
(2009, 1, '02-07-2009', 'BBD', 'SDN', 'GD', '3-0'),
(2009, 1, '02-07-2009', 'KKH', 'GDT', 'NT', '1-1'),
(2009, 2, '02-16-2009', 'SDN', 'KKH', 'CL', '2-2'),
(2009, 2, '02-16-2009', 'TPY', 'BBD', 'TH', '5-0'),
(2009, 3, '03-01-2009', 'TPY', 'GDT', 'TH', '0-2'),
(2009, 3, '03-01-2009', 'KKH', 'BBD', 'NT', '0-1'),
(2009, 4, '03-07-2009', 'KKH', 'TPY', 'NT', '1-0'),
(2009, 4, '03-07-2009', 'BBD', 'GDT', 'GD', '2-2');

INSERT INTO BANGXH (MACLB, NAM, VONG, SOTRAN, THANG, HOA, THUA, HIEUSO, DIEM, HANG) VALUES
('BBD',2009,1,1,1,0,0,'3-0',3,1),
('KKH',2009,1,1,0,1,0,'1-1',1,2),
('GDT',2009,1,1,0,1,0,'1-1',1,3),
('TPY',2009,1,0,0,0,0,'0-0',0,4),
('SDN',2009,1,1,0,0,1,'0-3',0,5),

('TPY',2009,2,1,1,0,0,'5-0',3,1),
('BBD',2009,2,2,1,0,1,'3-5',3,2),
('KKH',2009,2,2,0,2,0,'3-3',2,3),
('GDT',2009,2,1,0,1,0,'1-1',1,4),
('SDN',2009,2,1,0,1,0,'2-2',1,5),

('BBD',2009,3,3,2,0,1,'4-5',6,1),
('GDT',2009,3,2,1,1,0,'3-1',4,2),
('TPY',2009,3,2,1,0,1,'5-2',3,3),
('KKH',2009,3,3,0,2,1,'3-4',2,4),
('SDN',2009,3,2,0,1,1,'2-5',1,5),

('BBD',2009,4,4,2,1,1,'6-7',7,1),
('GDT',2009,4,3,1,2,0,'5-1',5,2),
('KKH',2009,4,4,1,2,1,'4-4',5,3),
('TPY',2009,4,3,1,0,2,'5-3',3,4),
('SDN',2009,4,2,1,1,0,'2-5',1,5);

--d
USE MASTER;
GO

CREATE LOGIN BDAdmin WITH PASSWORD = '123';
CREATE LOGIN BDBK WITH PASSWORD = '123';
CREATE LOGIN BDRead WITH PASSWORD = '123';
CREATE LOGIN BDU01 WITH PASSWORD = '123';
CREATE LOGIN BDU02 WITH PASSWORD = '123';
CREATE LOGIN BDU03 WITH PASSWORD = '123';
CREATE LOGIN BDU04 WITH PASSWORD = '123';
CREATE LOGIN BDProfile WITH PASSWORD = '123';
GO

USE QUAN_LY_GIAI_BONG_DA;
GO

CREATE USER BDAdmin FOR LOGIN BDAdmin;
CREATE USER BDBK FOR LOGIN BDBK;
CREATE USER BDRead FOR LOGIN BDRead;
CREATE USER BDU01 FOR LOGIN BDU01;
CREATE USER BDU02 FOR LOGIN BDU02;
CREATE USER BDU03 FOR LOGIN BDU03;
CREATE USER BDU04 FOR LOGIN BDU04;
CREATE USER BDProfile FOR LOGIN BDProfile;
GO

ALTER ROLE db_owner ADD MEMBER BDAdmin;
GRANT BACKUP DATABASE TO BDBK;
ALTER ROLE db_datareader ADD MEMBER BDRead;
GRANT CREATE TABLE TO BDU01;
GRANT UPDATE TO BDU02;
GRANT SELECT, INSERT, DELETE, UPDATE ON CAULACBO TO BDU03;
GRANT SELECT, INSERT, DELETE, UPDATE ON CAUTHU TO BDU04;
DENY SELECT ON CAUTHU(NGAYSINH) TO BDU04;
DENY UPDATE ON CAUTHU(VITRI) TO BDU04;
GRANT ALTER TRACE TO BDProfile;

--e
CREATE PROCEDURE SP_SEL_NO_ENCRYPT
	@TenCLB NVARCHAR(100),
	@TenQG NVARCHAR(100)
AS
BEGIN
	SELECT
	CT.MACT, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, CT.VITRI
	FROM CAUTHU CT
	JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB
	JOIN QUOCGIA QG ON CT.MAQG = QG.MAQG
	WHERE CLB.TENCLB = @TenCLB AND QG.TENQG = @TenQG
END;
GO

--f
CREATE PROCEDURE SP_SEL_ENCRYPT
	@TenCLB NVARCHAR(100),
	@TenQG NVARCHAR(100)
WITH ENCRYPTION
AS
BEGIN
	SELECT
	CT.MACT, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, CT.VITRI
	FROM CAUTHU CT
	JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB
	JOIN QUOCGIA QG ON CT.MAQG = QG.MAQG
	WHERE CLB.TENCLB = @TenCLB AND QG.TENQG = @TenQG
END;
GO

--g
EXEC SP_SEL_NO_ENCRYPT 
    @TenCLB = N'SHB Đà Nẵng',
    @TenQG = N'Brazil';

EXEC SP_SEL_ENCRYPT 
    @TenCLB = N'SHB Đà Nẵng',
    @TenQG = N'Brazil';

--h
DECLARE @i INT = 1;
DECLARE @sql NVARCHAR(MAX);

WHILE @i <= 100
BEGIN
    SET @sql = 'CREATE PROCEDURE SP_Test_' + CAST(@i AS NVARCHAR(3)) + ' 
                AS 
                BEGIN 
                    SELECT ' + CAST(@i AS NVARCHAR(3)) + ' AS Number; 
                END';
    
    EXEC sp_executesql @sql;
    SET @i = @i + 1;
END


DECLARE @sp_name NVARCHAR(MAX);
DECLARE @sp_definition NVARCHAR(MAX);
DECLARE @alter_script NVARCHAR(MAX);

DECLARE sp_cursor CURSOR FOR 
SELECT sm.object_id, OBJECT_NAME(sm.object_id) AS sp_name, sm.definition
FROM sys.sql_modules sm
JOIN sys.procedures p ON sm.object_id = p.object_id
WHERE p.is_ms_shipped = 0;

OPEN sp_cursor;
FETCH NEXT FROM sp_cursor INTO @sp_name, @sp_name, @sp_definition;

WHILE @@FETCH_STATUS = 0
BEGIN
    SET @alter_script = REPLACE(@sp_definition, 'CREATE PROCEDURE', 'ALTER PROCEDURE');
    SET @alter_script = REPLACE(@alter_script, 'create procedure', 'alter procedure');
    SET @alter_script = REPLACE(@alter_script, 'CREATE PROC', 'ALTER PROC');

    IF CHARINDEX('WITH ENCRYPTION', UPPER(@alter_script)) = 0
    BEGIN
        SET @alter_script = STUFF(@alter_script, CHARINDEX('AS', UPPER(@alter_script)), 0, 'WITH ENCRYPTION ');
        
        EXEC sp_executesql @alter_script;
        PRINT 'Encrypt SP: ' + @sp_name;
    END

    FETCH NEXT FROM sp_cursor INTO @sp_name, @sp_name, @sp_definition;
END

CLOSE sp_cursor;
DEALLOCATE sp_cursor;
GO

DECLARE @i INT = 1;
DECLARE @sql NVARCHAR(MAX);

WHILE @i <= 100
BEGIN
    SET @sql = 'DROP PROCEDURE IF EXISTS SP_Test_' + CAST(@i AS NVARCHAR(3));
    
    EXEC sp_executesql @sql;
    SET @i = @i + 1;
END