
-- i: 
--=============================================================================
--CREATE VIEWS
--=============================================================================

--1
CREATE OR ALTER VIEW vCau1 AS
SELECT MACT, HOTEN, NGAYSINH, DIACHI, VITRI
FROM CAUTHU CT JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB
                JOIN QUOCGIA QG ON CT.MAQG = QG.MAQG
WHERE CLB.TENCLB = N'SHB Đà Nẵng' AND QG.TENQG = N'Brazil';
GO

--2
CREATE OR ALTER VIEW vCau2 AS
SELECT TD.MATRAN, TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
FROM TRANDAU TD JOIN SANVD SVD ON TD.MASAN = SVD.MASAN
                JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
                JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
WHERE TD.NAM = 2009 AND TD.VONG = 3;
GO

--3
CREATE OR ALTER VIEW vCau3 AS
SELECT HLV.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI, HC.VAITRO, CLB.TENCLB
FROM HUANLUYENVIEN HLV
    JOIN HLV_CLB HC ON HLV.MAHLV = HC.MAHLV
    JOIN CAULACBO CLB ON HC.MACLB = CLB.MACLB
    JOIN QUOCGIA QG ON HLV.MAQG = QG.MAQG
WHERE QG.TENQG = N'Việt Nam';
GO

--4
CREATE OR ALTER VIEW vCau4 AS
SELECT CLB.MACLB, CLB.TENCLB, SVD.TENSAN, SVD.DIACHI, CT.SOLUONG
FROM CAULACBO CLB
    JOIN SANVD SVD ON CLB.MASAN = SVD.MASAN
    JOIN (SELECT MACLB, COUNT(CT.MACT) AS SOLUONG 
          FROM CAUTHU CT JOIN QUOCGIA QG ON CT.MAQG = QG.MAQG
          WHERE QG.TENQG != N'Việt Nam'
          GROUP BY MACLB) AS CT ON CLB.MACLB = CT.MACLB
WHERE CT.SOLUONG > 2;
GO 

--5
CREATE OR ALTER VIEW vCau5 AS 
SELECT T.TENTINH, COUNT(CT.MACT) AS SOLUONG_TIENDAO
FROM CAULACBO CLB
     JOIN TINH T ON CLB.MATINH = T.MATINH
     LEFT JOIN (SELECT MACT, MACLB, VITRI FROM CAUTHU WHERE VITRI = N'Tiền đạo') AS CT ON CLB.MACLB = CT.MACLB
GROUP BY T.MATINH, T.TENTINH
GO

--6
CREATE OR ALTER VIEW vCau6 AS
SELECT CLB.TENCLB, T.TENTINH
FROM CAULACBO CLB 
    JOIN TINH T ON CLB.MATINH = T.MATINH
    JOIN BANGXH BXH ON CLB.MACLB = BXH.MACLB
WHERE BXH.VONG = 3 AND BXH.NAM = 2009 AND BXH.HANG = 1;
GO

--7
CREATE OR ALTER VIEW vCau7 AS
SELECT DISTINCT HLV.TENHLV
FROM HUANLUYENVIEN HLV JOIN HLV_CLB HC ON HLV.MAHLV = HC.MAHLV
WHERE HLV.DIENTHOAI IS NULL;
GO

--8
CREATE OR ALTER VIEW vCau8 AS
SELECT HLV.MAHLV, HLV.TENHLV
FROM HUANLUYENVIEN HLV JOIN QUOCGIA QG ON HLV.MAQG = QG.MAQG
WHERE QG.TENQG = N'Việt Nam' AND HLV.MAHLV NOT IN (SELECT MAHLV FROM HLV_CLB);
GO

--9
CREATE OR ALTER VIEW vCau9 AS
SELECT TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
FROM TRANDAU TD 
    JOIN SANVD SVD ON TD.MASAN = SVD.MASAN
    JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
    JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
WHERE CLB1.MACLB = (SELECT BXH.MACLB
                    FROM BANGXH BXH 
                    WHERE BXH.VONG = 3 AND BXH.NAM = 2009 AND BXH.HANG = 1)
    OR CLB2.MACLB = (SELECT BXH.MACLB
                    FROM BANGXH BXH
                    WHERE BXH.VONG = 3 AND BXH.NAM = 2009 AND BXH.HANG = 1);
GO

--10
CREATE OR ALTER VIEW vCau10 AS
SELECT TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, TD.KETQUA
FROM TRANDAU TD 
    JOIN SANVD SVD ON TD.MASAN = SVD.MASAN
    JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
    JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
WHERE CLB1.MACLB = (SELECT BXH.MACLB
                    FROM BANGXH BXH 
                    WHERE BXH.VONG = 3 AND BXH.NAM = 2009 AND BXH.HANG = (SELECT MAX(HANG)
                                                                      FROM BANGXH
                                                                      WHERE VONG = 3 AND NAM = 2009))
    OR CLB2.MACLB = (SELECT BXH.MACLB
                    FROM BANGXH BXH
                    WHERE BXH.VONG = 3 AND BXH.NAM = 2009 AND BXH.HANG = (SELECT MAX(HANG)
                                                                      FROM BANGXH
                                                                      WHERE VONG = 3 AND NAM = 2009));
GO

--=============================================================================
--GRANT PRIVILEGES
--=============================================================================
--1
GRANT SELECT ON vCau1 TO BDRead;
GRANT SELECT ON vCau2 TO BDRead;
GRANT SELECT ON vCau3 TO BDRead;
GRANT SELECT ON vCau4 TO BDRead;
GRANT SELECT ON vCau5 TO BDRead;
GRANT SELECT ON vCau6 TO BDRead;
GRANT SELECT ON vCau7 TO BDRead;
GRANT SELECT ON vCau8 TO BDRead;
GRANT SELECT ON vCau9 TO BDRead;
GRANT SELECT ON vCau10 TO BDRead;

--2
GRANT SELECT ON vCau5 TO BDU01;
GRANT SELECT ON vCau6 TO BDU01;
GRANT SELECT ON vCau7 TO BDU01;
GRANT SELECT ON vCau8 TO BDU01;
GRANT SELECT ON vCau9 TO BDU01;
GRANT SELECT ON vCau10 TO BDU01;

--3
GRANT SELECT ON vCau1 TO BDU03;
GRANT SELECT ON vCau2 TO BDU03;
GRANT SELECT ON vCau3 TO BDU03;
GRANT SELECT ON vCau4 TO BDU03;

--4
GRANT SELECT ON vCau1 TO BDU04;
GRANT SELECT ON vCau2 TO BDU04;
GRANT SELECT ON vCau3 TO BDU04;
GRANT SELECT ON vCau4 TO BDU04;

-- --============================================================================
-- -- TEST: granted privileges
-- --============================================================================
-- -- 1. BDRead
-- SELECT * FROM vCau1
-- SELECT * FROM vCau5

-- -- 2. BDU01
-- SELECT * FROM vCau2
-- SELECT * FROM vCau10

-- -- 3. BDU03
-- SELECT * FROM vCau1
-- SELECT * FROM vCau2
-- SELECT * FROM vCau3
-- SELECT * FROM vCau4

-- -- 4. BDU04
-- SELECT * FROM vCau1
-- SELECT * FROM vCau2
-- SELECT * FROM vCau3
-- SELECT * FROM vCau4



--j