CREATE DATABASE QLSVNhom
GO USE QLSVNhom;
CREATE TABLE SINHVIEN (
	MASV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL UNIQUE,
	MATKHAU VARBINARY(MAX) NOT NULL
);
CREATE TABLE NHANVIEN (
	MANV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL UNIQUE,
	MATKHAU VARBINARY(MAX) NOT NULL,
	PUBKEY VARCHAR(20)
);
CREATE TABLE LOP (
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
);
CREATE TABLE HOCPHAN (
	MAHP VARCHAR(20) PRIMARY KEY,
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT
);
CREATE TABLE BANGDIEM (
	MASV VARCHAR(20),
	MAHP VARCHAR(20),
	DIEMTHI VARBINARY(MAX),
	PRIMARY KEY(MASV, MAHP)
);
ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV);
ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP);
--c
CREATE
OR ALTER PROCEDURE SP_INS_PUBLIC_NHANVIEN @MANV NVARCHAR(20),
@HOTEN NVARCHAR(100),
@EMAIL VARCHAR(20),
@LUONGCB INT,
@TENDN NVARCHAR(100),
@MK NVARCHAR(100) AS BEGIN
SET NOCOUNT ON;
DECLARE @MATKHAU_HASH VARBINARY(MAX);
DECLARE @LUONG_ENCRYPT VARBINARY(MAX);
DECLARE @SQL NVARCHAR(MAX);
SET @MATKHAU_HASH = HASHBYTES('SHA2_512', @MK);
IF NOT EXISTS (
	SELECT *
	FROM sys.asymmetric_keys
	WHERE name = @MANV
) BEGIN
SET @SQL = '
			CREATE ASYMMETRIC KEY [' + @MANV + ']
			WITH ALGORITHM = RSA_2048
			ENCRYPTION BY PASSWORD = ''' + @MK + '''
		';
EXEC(@SQL);
END
SET @LUONG_ENCRYPT = EncryptByAsymKey(
		AsymKey_ID(@MANV),
		CAST(@LUONGCB AS VARBINARY)
	);
INSERT INTO NHANVIEN(
		MANV,
		HOTEN,
		EMAIL,
		LUONG,
		TENDN,
		MATKHAU,
		PUBKEY
	)
VALUES (
		@MANV,
		@HOTEN,
		@EMAIL,
		@LUONG_ENCRYPT,
		@TENDN,
		@MATKHAU_HASH,
		@MANV
	)
END;
CREATE
OR ALTER PROCEDURE SP_SEL_PUBLIC_NHANVIEN @TENDN NVARCHAR(100),
@MK NVARCHAR(100) AS BEGIN
SET NOCOUNT ON;
DECLARE @MANV NVARCHAR(20);
DECLARE @LUONG_ENCRYPT VARBINARY(MAX);
DECLARE @LUONGCB INT;
DECLARE @MK_INPUT VARBINARY(MAX);
SELECT @MANV = MANV,
	@LUONG_ENCRYPT = LUONG
FROM NHANVIEN
WHERE TENDN = @TENDN;
IF @MANV IS NULL BEGIN PRINT N 'TENDN NOT EXISTS';
RETURN;
END
SET @MK_INPUT = HASHBYTES('SHA2_512', @MK);
IF NOT EXISTS (
	SELECT 1
	FROM NHANVIEN
	WHERE TENDN = @TENDN
		AND MATKHAU = @MK_INPUT
) BEGIN PRINT N'MAT KHAU ERROR';
RETURN;
END
SET @LUONGCB = CAST(
		DecryptByAsymKey(AsymKey_ID(@MANV), @LUONG_ENCRYPT, @MK) AS INT
	);
SELECT MANV,
	HOTEN,
	EMAIL,
	@LUONGCB AS LUONGCB
FROM NHANVIEN
WHERE TENDN = @TENDN;
END;