USE QLSVNhom;

-- quản lý đăng nhập
GO 
CREATE
    OR ALTER PROCEDURE SP_SEL_PUBLIC_NHANVIEN @TENDN NVARCHAR(100),
    @MK NVARCHAR(100) AS BEGIN
SET NOCOUNT ON;
DECLARE @MANV NVARCHAR(20);
DECLARE @LUONG_ENCRYPT VARBINARY(MAX);
SELECT @MANV = MANV,
    @LUONG_ENCRYPT = LUONG
FROM NHANVIEN
WHERE TENDN = @TENDN;
IF @MANV IS NULL BEGIN PRINT N'TENDN NOT EXISTS';
RETURN;
END IF NOT EXISTS (
    SELECT 1
    FROM NHANVIEN
    WHERE TENDN = @TENDN
        AND MATKHAU = HASHBYTES('SHA2_512', @MK)
) BEGIN PRINT N'MAT KHAU ERROR';
RETURN;
END
DECLARE @LUONGCB INT;
SET @LUONGCB = CAST(
        DecryptByAsymKey(AsymKey_ID(@MANV), @LUONG_ENCRYPT, @MK) AS INT
    );
SELECT MANV,
    HOTEN,
    EMAIL,
    @LUONGCB AS LUONGCB,
    PUBKEY
FROM NHANVIEN
WHERE TENDN = @TENDN;
END

-- quản lý lớp học
GO 
CREATE OR ALTER PROCEDURE SP_SEL_LOP AS BEGIN
SET NOCOUNT ON;
SELECT L.MALOP,
    L.TENLOP,
    L.MANV,
    N.HOTEN AS TEN_GVCN
FROM LOP L
    LEFT JOIN NHANVIEN N ON L.MANV = N.MANV
ORDER BY L.MALOP;
END

GO 
CREATE
    OR ALTER PROCEDURE SP_INS_LOP @MALOP VARCHAR(20),
    @TENLOP NVARCHAR(100),
    @MANV VARCHAR(20) AS BEGIN
SET NOCOUNT ON;
INSERT INTO LOP (MALOP, TENLOP, MANV)
VALUES (@MALOP, @TENLOP, @MANV);
END

GO 
CREATE
    OR ALTER PROCEDURE SP_UPD_LOP @MALOP VARCHAR(20),
    @TENLOP NVARCHAR(100),
    @MANV VARCHAR(20) AS BEGIN
SET NOCOUNT ON;
UPDATE LOP
SET TENLOP = @TENLOP,
    MANV = @MANV
WHERE MALOP = @MALOP;
END

GO 
CREATE
    OR ALTER PROCEDURE SP_DEL_LOP @MALOP VARCHAR(20) AS BEGIN
SET NOCOUNT ON;
UPDATE SINHVIEN
SET MALOP = NULL
WHERE MALOP = @MALOP;
DELETE FROM LOP
WHERE MALOP = @MALOP;
END
GO