CREATE DATABASE QLSVNhom
GO
USE QLSVNhom;

CREATE TABLE SINHVIEN (
	MASV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL UNIQUE,
	MATKHAU VARBINARY(MAX) NOT NULL
);

CREATE TABLE NHANVIEN (
	MANV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL UNIQUE,
	MATKHAU VARBINARY(MAX) NOT NULL,
	PUBKEY VARCHAR(20),
    ISADMIN BIT NOT NULL DEFAULT 0
);

CREATE TABLE LOP (
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
);

CREATE TABLE HOCPHAN (
	MAHP VARCHAR(20) PRIMARY KEY,
	TENHP NVARCHAR(100) NOT NULL,
	SOTC INT
);

CREATE TABLE BANGDIEM (
	MASV VARCHAR(20),
	MAHP VARCHAR(20),
	DIEMTHI VARBINARY(MAX),

	PRIMARY KEY(MASV, MAHP)
);

ALTER TABLE SINHVIEN
ADD CONSTRAINT FK_SINHVIEN_LOP
FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_NHANVIEN
FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_SINHVIEN
FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV);

ALTER TABLE BANGDIEM
ADD CONSTRAINT FK_BANGDIEM_HOCPHAN
FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP);

--b
CREATE OR ALTER PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN
	@MANV VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(20),
    @LUONG VARBINARY(MAX),
    @TENDN NVARCHAR(100),
    @MK VARBINARY(MAX),
    @PUB VARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION;
    BEGIN TRY
        IF EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV)
            THROW 50001, N'MANV ALREADY EXISTS.', 1;

        IF EXISTS (SELECT 1 FROM NHANVIEN WHERE TENDN = @TENDN)
            THROW 50002, N'TENDN ALREADY EXISTS.', 1;

        INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
        VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MK, @PUB);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK;
        DECLARE @ErrMsg NVARCHAR(4000) = ERROR_MESSAGE();
        RAISERROR(@ErrMsg, 16, 1);
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
    @TENDN NVARCHAR(100),
    @MK VARBINARY(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT
        n.MANV,
        n.HOTEN,
        n.EMAIL,
        n.LUONG,
        n.PUBKEY,
        n.TENDN
    FROM NHANVIEN n
    WHERE n.TENDN = @TENDN COLLATE SQL_Latin1_General_CP1_CS_AS
      AND n.MATKHAU = @MK;
END
GO
